name: update
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */2 * * *"
  push:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Nix
        uses: cachix/install-nix-action@v16
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Update flake
        run: "nix flake update"

      - name: Commit changes
        uses: EndBug/add-and-commit@v7.5.0
        with:
          default_author: github_actions
          message: "Update flake"
          add: "flake.lock"
